# Generated by Django 4.2.7

from django.db import migrations
from django.contrib.auth.models import User
from events.models import UserProfile


def create_superadmin(apps, schema_editor):
    """Créer un super admin lors de la migration"""
    # Créer le super admin
    username = "admin"
    password = "admin123"
    email = "admin@eventmanagement.com"
    
    # Supprimer l'utilisateur s'il existe déjà
    try:
        existing_user = User.objects.get(username=username)
        existing_user.delete()
    except User.DoesNotExist:
        pass
    
    # Créer le super admin
    user = User.objects.create_superuser(
        username=username,
        email=email,
        password=password
    )
    
    # Créer le profil utilisateur
    try:
        profile = UserProfile.objects.get(user=user)
        profile.role = 'super_admin'
        profile.phone_number = '+1234567890'
        profile.bio = 'Super administrateur'
        profile.save()
    except UserProfile.DoesNotExist:
        UserProfile.objects.create(
            user=user,
            role='super_admin',
            phone_number='+1234567890',
            bio='Super administrateur'
        )


def reverse_create_superadmin(apps, schema_editor):
    """Supprimer le super admin lors de la migration inverse"""
    try:
        user = User.objects.get(username="admin")
        user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superadmin, reverse_create_superadmin),
    ]
