# Generated by Django 4.2.7 on 2025-08-12 01:27

from django.db import migrations


def add_missing_qr_columns(apps, schema_editor):
    # Ajouter qr_token si manquant
    schema_editor.execute(
        """
        ALTER TABLE `events_eventregistration`
        ADD COLUMN IF NOT EXISTS `qr_token` varchar(64) UNIQUE NULL;
        """
    )
    # Ajouter qr_code si manquant
    schema_editor.execute(
        """
        ALTER TABLE `events_eventregistration`
        ADD COLUMN IF NOT EXISTS `qr_code` varchar(100) NULL;
        """
    )


def remove_columns(apps, schema_editor):
    # Suppression conditionnelle (ignorer les erreurs si colonne absente)
    try:
        schema_editor.execute(
            "ALTER TABLE `events_eventregistration` DROP COLUMN `qr_code`;"
        )
    except Exception:
        pass
    try:
        schema_editor.execute(
            "ALTER TABLE `events_eventregistration` DROP COLUMN `qr_token`;"
        )
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventregistration_price_paid_and_more'),
    ]

    # Exécuter hors transaction pour autoriser DDL MySQL/MariaDB
    atomic = False

    operations = [
        migrations.RunPython(add_missing_qr_columns, reverse_code=remove_columns),
    ]
