services:
  - type: web
    name: event-management-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn event_management.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: event_management.settings_render
      - key: PYTHON_VERSION
        value: 3.10.12