services:
  - type: web
    name: event-management-backend
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn event_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: event_management.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: event-management-backend-7uux.onrender.com
    healthCheckPath: /api/